### ISSUE TITLE
Docker container bad `glibc` version

### ISSUE THREAD

**Issue by Laura7089** [apexskier/strava-tile-proxy#5]
Running the container (whether I build it myself or not), I get:

```
strava-tile-proxy-1  | /binary: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /binary)
strava-tile-proxy-1  | /binary: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /binary)
```

**Comment by Laura7089** [comment]
Presumably this is caused by a libc version mismatch between the pinned go image version and the debian one.

**Comment by apexskier** [comment]
I've seen this elsewhere with go < 1.20.4 and Debian 10. Thanks for the report.
